In [8]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline


import matplotlib.pyplot as plt


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('D:\8th sem\Intrusion Detection System'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


df_train = pd.read_csv('./nsl-kdd/KDDTrain+.txt')
df_test = pd.read_csv('./nsl-kdd/KDDTest+.txt')


<>:18: SyntaxWarning: invalid escape sequence '\8'
<>:18: SyntaxWarning: invalid escape sequence '\8'
C:\Users\sulav\AppData\Local\Temp\ipykernel_55520\1445710697.py:18: SyntaxWarning: invalid escape sequence '\8'
  for dirname, _, filenames in os.walk('D:\8th sem\Intrusion Detection System'):


In [9]:
df_train.head(10)

0  tcp    ftp_data   SF  491   0.1  0.2  0.3  0.4  0.5  ...  0.17  0.03  \
0  0  udp       other   SF  146     0    0    0    0    0  ...  0.00  0.60   
1  0  tcp     private   S0    0     0    0    0    0    0  ...  0.10  0.05   
2  0  tcp        http   SF  232  8153    0    0    0    0  ...  1.00  0.00   
3  0  tcp        http   SF  199   420    0    0    0    0  ...  1.00  0.00   
4  0  tcp     private  REJ    0     0    0    0    0    0  ...  0.07  0.07   
5  0  tcp     private   S0    0     0    0    0    0    0  ...  0.04  0.05   
6  0  tcp     private   S0    0     0    0    0    0    0  ...  0.06  0.07   
7  0  tcp  remote_job   S0    0     0    0    0    0    0  ...  0.09  0.05   
8  0  tcp     private   S0    0     0    0    0    0    0  ...  0.05  0.06   
9  0  tcp     private  REJ    0     0    0    0    0    0  ...  0.05  0.07   

   0.17.1  0.00.6  0.00.7  0.00.8  0.05  0.00.9   normal  20  
0    0.88    0.00    0.00    0.00   0.0    0.00   normal  15  
1    0.00    0.00    1.00    1.00   0.0    0.00  neptune  19  
2    0.03    0.04    0.03    0.01   0.0    0.01   normal  21  
3    0.00    0.00    0.00    0.00   0.0    0.00   normal  21  
4    0.00    0.00    0.00    0.00   1.0    1.00  neptune  21  
5    0.00    0.00    1.00    1.00   0.0    0.00  neptune  21  
6    0.00    0.00    1.00    1.00   0.0    0.00  neptune  21  
7    0.00    0.00    1.00    1.00   0.0    0.00  neptune  21  
8    0.00    0.00    1.00    1.00   0.0    0.00  neptune  21  
9    0.00    0.00    0.00    0.00   1.0    1.00  neptune  21  

[10 rows x 43 columns]

In [10]:
df_test.head(10)

0   tcp   private   REJ    0.1    0.2  0.3  0.4  0.5  0.6  ...  0.04.1  \
0  0   tcp   private   REJ      0      0    0    0    0    0  ...    0.00   
1  2   tcp  ftp_data    SF  12983      0    0    0    0    0  ...    0.61   
2  0  icmp     eco_i    SF     20      0    0    0    0    0  ...    1.00   
3  1   tcp    telnet  RSTO      0     15    0    0    0    0  ...    0.31   
4  0   tcp      http    SF    267  14515    0    0    0    0  ...    1.00   
5  0   tcp      smtp    SF   1022    387    0    0    0    0  ...    0.11   
6  0   tcp    telnet    SF    129    174    0    0    0    0  ...    1.00   
7  0   tcp      http    SF    327    467    0    0    0    0  ...    1.00   
8  0   tcp       ftp    SF     26    157    0    0    0    0  ...    0.50   
9  0   tcp    telnet    SF      0      0    0    0    0    0  ...    0.50   

   0.06.1  0.00.3  0.00.4  0.00.5  0.00.6  1.00.2  1.00.3       neptune  21  
0    0.06    0.00    0.00    0.00    0.00    1.00    1.00       neptune  21  
1    0.04    0.61    0.02    0.00    0.00    0.00    0.00        normal  21  
2    0.00    1.00    0.28    0.00    0.00    0.00    0.00         saint  15  
3    0.17    0.03    0.02    0.00    0.00    0.83    0.71         mscan  11  
4    0.00    0.01    0.03    0.01    0.00    0.00    0.00        normal  21  
5    0.72    0.00    0.00    0.00    0.00    0.72    0.04        normal  21  
6    0.00    0.00    0.00    0.01    0.01    0.02    0.02  guess_passwd  15  
7    0.00    0.01    0.03    0.00    0.00    0.00    0.00        normal  21  
8    0.08    0.02    0.00    0.00    0.00    0.00    0.00  guess_passwd   7  
9    0.01    0.00    0.00    0.00    0.00    0.66    0.32         mscan   9  

[10 rows x 43 columns]

In [11]:
df_train.columns

Index(['0', 'tcp', 'ftp_data', 'SF', '491', '0.1', '0.2', '0.3', '0.4', '0.5',
       '0.6', '0.7', '0.8', '0.9', '0.10', '0.11', '0.12', '0.13', '0.14',
       '0.15', '0.16', '0.18', '2', '2.1', '0.00', '0.00.1', '0.00.2',
       '0.00.3', '1.00', '0.00.4', '0.00.5', '150', '25', '0.17', '0.03',
       '0.17.1', '0.00.6', '0.00.7', '0.00.8', '0.05', '0.00.9', 'normal',
       '20'],
      dtype='object')

In [12]:
columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
           'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted',
           'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
           'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate',
           'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
           'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
           'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
           'dst_host_srv_rerror_rate', 'attack', 'level']

df_train.columns = columns
df_test.columns = columns

In [13]:
df_train['protocol_type'].unique(), df_train['service'].unique(), df_train['flag'].unique()

(array(['udp', 'tcp', 'icmp'], dtype=object),
 array(['other', 'private', 'http', 'remote_job', 'ftp_data', 'name',
        'netbios_ns', 'eco_i', 'mtp', 'telnet', 'finger', 'domain_u',
        'supdup', 'uucp_path', 'Z39_50', 'smtp', 'csnet_ns', 'uucp',
        'netbios_dgm', 'urp_i', 'auth', 'domain', 'ftp', 'bgp', 'ldap',
        'ecr_i', 'gopher', 'vmnet', 'systat', 'http_443', 'efs', 'whois',
        'imap4', 'iso_tsap', 'echo', 'klogin', 'link', 'sunrpc', 'login',
        'kshell', 'sql_net', 'time', 'hostnames', 'exec', 'ntp_u',
        'discard', 'nntp', 'courier', 'ctf', 'ssh', 'daytime', 'shell',
        'netstat', 'pop_3', 'nnsp', 'IRC', 'pop_2', 'printer', 'tim_i',
        'pm_dump', 'red_i', 'netbios_ssn', 'rje', 'X11', 'urh_i',
        'http_8001', 'tftp_u', 'harvest'], dtype=object),
 array(['SF', 'S0', 'REJ', 'RSTR', 'SH', 'RSTO', 'S1', 'RSTOS0', 'S3',
        'S2', 'OTH'], dtype=object))

In [14]:
df_train['attack'].unique()

array(['normal', 'neptune', 'warezclient', 'ipsweep', 'portsweep',
       'teardrop', 'nmap', 'satan', 'smurf', 'pod', 'back',
       'guess_passwd', 'ftp_write', 'multihop', 'rootkit',
       'buffer_overflow', 'imap', 'warezmaster', 'phf', 'land',
       'loadmodule', 'spy', 'perl'], dtype=object)

In [15]:
full_data = pd.concat([df_train, df_test], ignore_index=True)

label_encoders = {}
for column in ['protocol_type', 'service', 'flag']:
    le = LabelEncoder()
    full_data[column] = le.fit_transform(full_data[column])
    label_encoders[column] = le

X = full_data.drop(['attack', 'level'], axis=1)
y = full_data['attack']

In [16]:
X['protocol_type'].unique(), X['service'].unique(), X['flag'].unique()

(array([2, 1, 0]),
 array([42, 47, 23, 49, 19, 34, 36, 13, 33, 58, 17, 11, 56, 65,  2, 52,  6,
        64, 35, 63,  3, 10, 18,  4, 30, 14, 20, 66, 57, 24, 15, 67, 26, 27,
        12, 28, 31, 55, 32, 29, 53, 61, 22, 16, 41,  9, 40,  5,  7, 54,  8,
        51, 38, 45, 39,  0, 44, 46, 60, 43, 48, 37, 50,  1, 62, 25, 59, 21]),
 array([ 9,  5,  1,  4, 10,  2,  6,  3,  8,  7,  0]))

In [17]:
import joblib

In [18]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', ExtraTreesClassifier()),
])

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', ExtraTreesClassifier())])

In [20]:
data = [[0,1,7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,251,3,0.00,0.00,1.00,1.00,0.01,0.06,0.00,255,3,0.01,0.06,0.00,0.00,0.00,0.00,1.00,1.00]]

In [21]:
pipeline.predict(data)

c:\My_Files\My_Learnings\Machine_Learning\Intrusion-Detection-System\myenv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array(['neptune'], dtype=object)

In [22]:
joblib.dump(pipeline, 'extra_trees_pipeline.pkl')

['extra_trees_pipeline.pkl']